### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#46]
Hi @etiennebacher,

I recently spoke to @rempsyc (who has been contributing to `easystats`) and we agreed to work together to improve some aspects of `altdoc`. To minimize your workload, I propose that in the initial phases, Rémi tries to put some code together, and I do code review. 

This effort is formally part of my `marginaleffects` book project, so the initial contributions would be targeted at some features that I need for that. The features I am thinking about (in order from most important):

- [x] Complete, test and merge https://github.com/etiennebacher/altdoc/pull/48
- [ ] Complete, test, document, and merge https://github.com/etiennebacher/altdoc/pull/39
- [x] Complete and test this PR: https://github.com/etiennebacher/altdoc/pull/44 The concept is to convert .Rd function documentation files to .Rmarkdown or Quarto, and then to render those files to Github Flavored Markdown. This allows us to execute examples without having to do parse, extract the examples, and `eval()`, which is complicated and error-prone.
- [x] See if there is anything to learn from this `rd2qmd()` function, and improve the conversion in `altdoc` if necessary: https://github.com/vincentarelbundock/marginaleffects/blob/main/book/utils/utils.R#L79
- [ ] Convert the `marginaleffects` book to `altdoc` as a hard test case (it's pretty complicated).
- [ ] See if we can close some other issues in the repo (if time/interest).
- [ ] See if we can improve the documentation (if time/interest)

What do you think?

**Comment by etiennebacher** [comment]
Hi @vincentarelbundock and @rempsyc, thanks for making this roadmap and wanting to improve `altdoc`. It's a small world, always collaborating with the same 5-10 people :)

Here are some thoughts, happy to discuss more about this.

**Contributions:** I don't think I'll be able to properly review the changes in this package so I can give to you two the right to review and merge PRs (I'll protect the `main` branch to make it PR-only). 

**Features:** I'm completely fine with improving the functionalities of `altdoc`, indeed it would be great to wrap up the PR on Quarto and the one on evaluating the examples. However, I'd like these changes to meet two requirements: 1) they are available for all packages (not something that only works because of some something specific in `marginaleffects` only), and 2) they don't break existing tests (this can be changed later if needed, but ideally they won't break). Maybe you had already taken this into account, sorry if this adds more work.

Just a note for the PR on evaluating the examples, I tried a bit when you contacted me a few weeks ago but couldn't make it work in a general way. There's still the issue of some tags like `@examplesIf` that simply disappear when we read the Rd file (cf #45) and this was super annoying when I tried my code on `datawizard` (the other packages in `easystats` also massively use `@examplesIf`). I couldn't find one perfect tool to handle the Rd files: if one worked fine for the examples, it couldn't handle some sections, or the output was really unclean, etc. So I'm curious to see your solution using `rd2qmd()`.

**Comment by vincentarelbundock** [comment]
Cool. All of this sounds good. Agreed on 

1. Preserving backward compatibility and tests
2. Not implementing marginaleffects-specific features. Because both R and I are pretty busy right now.

To set expectstions: I think this will be a long and slow process.

**Comment by vincentarelbundock** [comment]
FWIW, here's a rendered version of a Quarto document that I produced using `rd2qmd()` and some easy to automate manual tweaks for the `parameters::standardize_parameters.Rd` docs. That function includes a `@examplesIf` tag, and the render looks pretty great for a first attempt.

https://arelbundock.com/standardize_parameters.html

**Comment by etiennebacher** [comment]
> FWIW, here's a rendered version of a Quarto document that I produced using rd2qmd() 

Looks great! The only drawback is that it requires having quarto installed but it's already nice to have this.

I've invited @rempsyc and you to the repo so you should have the right to review and merge PRs (tests must pass and there must be approval of one of you). The `main` branch is protected so it should be impossible to push directly there.

Ping me if some of the settings don't work.

**Comment by vincentarelbundock** [comment]
Great, thanks!

> The only drawback is that it requires having quarto installed

Oh, I think the same concept/workflow will work for Rmarkdown too.

**Comment by rempsyc** [comment]
Just so that I understand clearly what "testing" means in the context of `altdoc`, my understanding is that:

1. The site renders without error
2. README renders correctly
3. NEWS (changelog) renders correctly
4. Reference renders correctly
5. Examples render correctly
6. Examples preserve tags like `@examplesIf`
7. Vignettes render correctly

With `datawizard`, I use:

``` r
library(altdoc)
use_docute()
```

And steps 1:4 succeed.

Step 5: Examples are "rendered" but not executed (presumably fixed in #44).

Step 6: tags don't appear in the rendered website, but neither do they using `pkgdown`. That said, the resulting `reference.md` file also doesn't contain the tags (I suppose they should if the examples are to be executed from that file later in the process).

Step 7: Vignettes: continued in #48
