### ISSUE TITLE
Future improvement ideas

### ISSUE THREAD

**Issue by rempsyc** [etiennebacher/altdoc#51]
(Work in progress)

---

- [x] 1. Automatically add logo to README without having to specify it explicitly in the README file, like in `pkgdown` (discussed in #50).
- [x] 2. Fix inclusion of images generated through code in vignettes (#55)
- [x] 3. Bring back automatical addition of vignettes to the site structure file, but as an optional argument with (probably) a default = `FALSE` to avoid messing custom structures (requires finding a way to do it for `index.html` in the case of `use_docute()`, (#56, fixed in #55)
- [ ] 4. Convert function calls to proper URLS like in `pkgdown` (discussed in #48)

**Comment by vincentarelbundock** [comment]
Opening a new issue for the last feature
